0. Run Python file

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,3 +1,8 @@
 #!/bin/bash
 
+if [ -z "$PYFILE" ]; then
+    echo "Error: PYFILE environment variable is not found."
+if [ ! -f "$PYFILE" ]; then
+    echo "Error: Python file '$PYFILE' not found."
+    exit 1
 python3 ./$PYFILE
